#!/bin/sh

if [ $# -eq 1 ]; then
  if [ "$1" = "-a" ]; then
    echo "enter standby..."
	stfbcontrol hd
	fp_control -l 0 1
	echo on > /proc/stb/avs/0/standby
	echo "done"
  elif [ "$1" = "-d" ]; then
	echo "end standby..."
       #enable hdmi
       stfbcontrol he
       echo off > /proc/stb/avs/0/standby
       fp_control -l 0 0
  fi
fi
