#! /bin/sh
#
# mountspark	Mount spark root as usb.
#
# chkconfig: S 39 0
#

if [ -f /lib/modules/$(uname -r)/kernel/fs/yaffs2/yaffs.ko ]; then
	MOUNT=$(mount | grep "/media/usb ")
	if [ -z "$MOUNT" ]; then
		modprobe yaffs
		if [ ! -d /media/usb ]; then
			mkdir /media/usb
		fi 
		echo "Mount /dev/mtdblock4 on /media/usb"
		mount -t yaffs2 /dev/mtdblock4 /media/usb
	fi
fi

#
# copy picon directories
#
echo "Copy picons from /media/usb to tmp..."
[ -f /media/usb/picon_tmp.tar ] && tar -xf /media/usb/picon_tmp.tar -C /tmp
[ ! -d /tmp/piconProv ] && [ -d /media/usb/piconProv ] && cp -R /media/usb/piconProv /tmp

exit 0

